# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo
    build: ./
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    env_file:
      - .env

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    env_file:
      - .env
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    expose:
      - "8081"
    restart: always